# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- deploy

pool:
  vmImage: ubuntu-latest

steps:
- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'
    checkLatest: true
- task: Yarn@3
  inputs:
    projectDirectory: '$(System.DefaultWorkingDirectory)'
    arguments: 'yarn install'
    productionMode: true


- task: Yarn@3
  inputs:
    projectDirectory: '$(System.DefaultWorkingDirectory)'
    arguments: 'yarn run build'

- task: CopyFiles@2

  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'

  inputs:

    Contents: 'build/**'

    TargetFolder: '$(Build.ArtifactStagingDirectory)'

    OverWrite: true



- task: PublishBuildArtifacts@1

  displayName: 'Publish Artifact: drop'

  
